"""
Column mapping dictionaries for Alpha Vantage to DB schema standardization.

These mappings are used by standardization utility functions to ensure
consistent column naming and typing for ingestion into your database.
"""

COMPANY_FUNDAMENTALS_MAP = {
    'Symbol': 'symbol',
    'AssetType': 'asset_type',
    'Name': 'name',
    'Description': 'description',
    'CIK': 'cik',
    'Exchange': 'exchange',
    'Currency': 'currency',
    'Country': 'country',
    'Sector': 'sector',
    'Industry': 'industry',
    'Address': 'address',
    'OfficialSite': 'official_site',
    'FiscalYearEnd': 'fiscal_year_end',
    'LatestQuarter': 'latest_quarter',
    'MarketCapitalization': 'market_capitalization',
    'EBITDA': 'ebitda',
    'PERatio': 'pe_ratio',
    'PEGRatio': 'peg_ratio',
    'BookValue': 'book_value',
    'DividendPerShare': 'dividend_per_share',
    'DividendYield': 'dividend_yield',
    'EPS': 'eps',
    'RevenuePerShareTTM': 'revenue_per_share_ttm',
    'ProfitMargin': 'profit_margin',
    'OperatingMarginTTM': 'operating_margin_ttm',
    'ReturnOnAssetsTTM': 'return_on_assets_ttm',
    'ReturnOnEquityTTM': 'return_on_equity_ttm',
    'RevenueTTM': 'revenue_ttm',
    'GrossProfitTTM': 'gross_profit_ttm',
    'DilutedEPSTTM': 'diluted_eps_ttm',
    'QuarterlyEarningsGrowthYOY': 'quarterly_earnings_growth_yoy',
    'QuarterlyRevenueGrowthYOY': 'quarterly_revenue_growth_yoy',
    'AnalystTargetPrice': 'analyst_target_price',
    'AnalystRatingStrongBuy': 'analyst_rating_strong_buy',
    'AnalystRatingBuy': 'analyst_rating_buy',
    'AnalystRatingHold': 'analyst_rating_hold',
    'AnalystRatingSell': 'analyst_rating_sell',
    'AnalystRatingStrongSell': 'analyst_rating_strong_sell',
    'TrailingPE': 'trailing_pe',
    'ForwardPE': 'forward_pe',
    'PriceToSalesRatioTTM': 'price_to_sales_ratio_ttm',
    'PriceToBookRatio': 'price_to_book_ratio',
    'EVToRevenue': 'ev_to_revenue',
    'EVToEBITDA': 'ev_to_ebitda',
    'Beta': 'beta',
    '52WeekHigh': 'fifty_two_week_high',
    '52WeekLow': 'fifty_two_week_low',
    '50DayMovingAverage': 'fifty_day_moving_average',
    '200DayMovingAverage': 'two_hundred_day_moving_average',
    'SharesOutstanding': 'shares_outstanding',
    'DividendDate': 'dividend_date',
    'ExDividendDate': 'ex_dividend_date'
}

COMPANY_FUNDAMENTALS_INT_COLUMNS = [
    "cik",
    "analyst_rating_strong_buy",
    "analyst_rating_buy",
    "analyst_rating_hold",
    "analyst_rating_sell",
    "analyst_rating_strong_sell",
    "shares_outstanding"
]

COMPANY_FUNDAMENTALS_FLOAT_COLUMNS = [
    "market_capitalization", "ebitda", "pe_ratio", "peg_ratio", "book_value",
    "dividend_per_share", "dividend_yield", "eps", "revenue_per_share_ttm",
    "profit_margin", "operating_margin_ttm", "return_on_assets_ttm",
    "return_on_equity_ttm", "revenue_ttm", "gross_profit_ttm", "diluted_eps_ttm",
    "quarterly_earnings_growth_yoy", "quarterly_revenue_growth_yoy",
    "analyst_target_price", "trailing_pe", "forward_pe", "price_to_sales_ratio_ttm",
    "price_to_book_ratio", "ev_to_revenue", "ev_to_ebitda", "beta",
    "fifty_two_week_high", "fifty_two_week_low", "fifty_day_moving_average",
    "two_hundred_day_moving_average"
]

ANNUAL_INCOME_STATEMENT_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'grossProfit': 'gross_profit',
    'totalRevenue': 'total_revenue',
    'costOfRevenue': 'cost_of_revenue',
    'costofGoodsAndServicesSold': 'cost_of_goods_and_services_sold',
    'operatingIncome': 'operating_income',
    'sellingGeneralAndAdministrative': 'selling_general_and_administrative',
    'researchAndDevelopment': 'research_and_development',
    'operatingExpenses': 'operating_expenses',
    'investmentIncomeNet': 'investment_income_net',
    'netInterestIncome': 'net_interest_income',
    'interestIncome': 'interest_income',
    'interestExpense': 'interest_expense',
    'nonInterestIncome': 'non_interest_income',
    'otherNonOperatingIncome': 'other_non_operating_income',
    'depreciation': 'depreciation',
    'depreciationAndAmortization': 'depreciation_and_amortization',
    'incomeBeforeTax': 'income_before_tax',
    'incomeTaxExpense': 'income_tax_expense',
    'interestAndDebtExpense': 'interest_and_debt_expense',
    'netIncomeFromContinuingOperations': 'net_income_from_continuing_operations',
    'comprehensiveIncomeNetOfTax': 'comprehensive_income_net_of_tax',
    'ebit': 'ebit',
    'ebitda': 'ebitda',
    'netIncome': 'net_income',
}


INCOME_STATEMENT_NUMERIC_COLUMNS = [
    'gross_profit', 'total_revenue', 'cost_of_revenue', 'cost_of_goods_and_services_sold',
    'operating_income', 'selling_general_and_administrative', 'research_and_development',
    'operating_expenses', 'investment_income_net', 'net_interest_income', 'interest_income',
    'interest_expense', 'non_interest_income', 'other_non_operating_income', 'depreciation',
    'depreciation_and_amortization', 'income_before_tax', 'income_tax_expense',
    'interest_and_debt_expense', 'net_income_from_continuing_operations',
    'comprehensive_income_net_of_tax', 'ebit', 'ebitda', 'net_income'
]

QUARTERLY_INCOME_STATEMENT_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'grossProfit': 'gross_profit',
    'totalRevenue': 'total_revenue',
    'costOfRevenue': 'cost_of_revenue',
    'costofGoodsAndServicesSold': 'cost_of_goods_and_services_sold',
    'operatingIncome': 'operating_income',
    'sellingGeneralAndAdministrative': 'selling_general_and_administrative',
    'researchAndDevelopment': 'research_and_development',
    'operatingExpenses': 'operating_expenses',
    'investmentIncomeNet': 'investment_income_net',
    'netInterestIncome': 'net_interest_income',
    'interestIncome': 'interest_income',
    'interestExpense': 'interest_expense',
    'nonInterestIncome': 'non_interest_income',
    'otherNonOperatingIncome': 'other_non_operating_income',
    'depreciation': 'depreciation',
    'depreciationAndAmortization': 'depreciation_and_amortization',
    'incomeBeforeTax': 'income_before_tax',
    'incomeTaxExpense': 'income_tax_expense',
    'interestAndDebtExpense': 'interest_and_debt_expense',
    'netIncomeFromContinuingOperations': 'net_income_from_continuing_operations',
    'comprehensiveIncomeNetOfTax': 'comprehensive_income_net_of_tax',
    'ebit': 'ebit',
    'ebitda': 'ebitda',
    'netIncome': 'net_income',
}


ANNUAL_BALANCE_SHEET_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'totalAssets': 'total_assets',
    'totalCurrentAssets': 'total_current_assets',
    'cashAndCashEquivalentsAtCarryingValue': 'cash_and_cash_equivalents',
    'cashAndShortTermInvestments': 'cash_and_short_term_investments',
    'inventory': 'inventory',
    'currentNetReceivables': 'current_net_receivables',
    'totalNonCurrentAssets': 'total_non_current_assets',
    'propertyPlantEquipment': 'property_plant_equipment',
    'accumulatedDepreciationAmortizationPPE': 'accumulated_depreciation_amortization_ppe',
    'intangibleAssets': 'intangible_assets',
    'goodwill': 'goodwill',
    'longTermInvestments': 'long_term_investments',
    'shortTermInvestments': 'short_term_investments',
    'otherCurrentAssets': 'other_current_assets',
    'otherNonCurrentAssets': 'other_non_current_assets',
    'totalLiabilities': 'total_liabilities',
    'totalCurrentLiabilities': 'total_current_liabilities',
    'currentAccountsPayable': 'current_accounts_payable',
    'deferredRevenue': 'deferred_revenue',
    'currentDebt': 'current_debt',
    'shortTermDebt': 'short_term_debt',
    'totalNonCurrentLiabilities': 'total_non_current_liabilities',
    'capitalLeaseObligations': 'capital_lease_obligations',
    'longTermDebt': 'long_term_debt',
    'shortLongTermDebtTotal': 'short_long_term_debt_total',
    'otherCurrentLiabilities': 'other_current_liabilities',
    'otherNonCurrentLiabilities': 'other_non_current_liabilities',
    'totalShareholderEquity': 'total_shareholder_equity',
    'treasuryStock': 'treasury_stock',
    'retainedEarnings': 'retained_earnings',
    'commonStock': 'common_stock',
    'commonStockSharesOutstanding': 'common_stock_shares_outstanding'
}

ANNUAL_BALANCE_SHEET_FLOAT_COLUMNS = [
    'total_assets', 'total_current_assets', 'cash_and_cash_equivalents',
    'cash_and_short_term_investments', 'inventory', 'current_net_receivables',
    'total_non_current_assets', 'property_plant_equipment', 'accumulated_depreciation_amortization_ppe',
    'intangible_assets', 'goodwill', 'long_term_investments', 'short_term_investments',
    'other_current_assets', 'other_non_current_assets', 'total_liabilities',
    'total_current_liabilities', 'current_accounts_payable', 'deferred_revenue',
    'current_debt', 'short_term_debt', 'total_non_current_liabilities', 'capital_lease_obligations',
    'long_term_debt', 'short_long_term_debt_total', 'other_current_liabilities',
    'other_non_current_liabilities', 'total_shareholder_equity', 'treasury_stock',
    'retained_earnings', 'common_stock'
]

ANNUAL_BALANCE_SHEET_INT_COLUMNS = [
    'common_stock_shares_outstanding'
]

QUARTERLY_BALANCE_SHEET_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'totalAssets': 'total_assets',
    'totalCurrentAssets': 'total_current_assets',
    'cashAndCashEquivalentsAtCarryingValue': 'cash_and_cash_equivalents',
    'cashAndShortTermInvestments': 'cash_and_short_term_investments',
    'inventory': 'inventory',
    'currentNetReceivables': 'current_net_receivables',
    'totalNonCurrentAssets': 'total_non_current_assets',
    'propertyPlantEquipment': 'property_plant_equipment',
    'accumulatedDepreciationAmortizationPPE': 'accumulated_depreciation_amortization_ppe',
    'intangibleAssets': 'intangible_assets',
    'intangibleAssetsExcludingGoodwill': 'intangible_assets_excluding_goodwill',
    'goodwill': 'goodwill',
    'investments': 'investments',
    'longTermInvestments': 'long_term_investments',
    'shortTermInvestments': 'short_term_investments',
    'otherCurrentAssets': 'other_current_assets',
    'otherNonCurrentAssets': 'other_non_current_assets',
    'totalLiabilities': 'total_liabilities',
    'totalCurrentLiabilities': 'total_current_liabilities',
    'currentAccountsPayable': 'current_accounts_payable',
    'deferredRevenue': 'deferred_revenue',
    'currentDebt': 'current_debt',
    'shortTermDebt': 'short_term_debt',
    'totalNonCurrentLiabilities': 'total_non_current_liabilities',
    'capitalLeaseObligations': 'capital_lease_obligations',
    'longTermDebt': 'long_term_debt',
    'currentLongTermDebt': 'current_long_term_debt',
    'longTermDebtNoncurrent': 'long_term_debt_noncurrent',
    'shortLongTermDebtTotal': 'short_long_term_debt_total',
    'otherCurrentLiabilities': 'other_current_liabilities',
    'otherNonCurrentLiabilities': 'other_non_current_liabilities',
    'totalShareholderEquity': 'total_shareholder_equity',
    'treasuryStock': 'treasury_stock',
    'retainedEarnings': 'retained_earnings',
    'commonStock': 'common_stock',
    'commonStockSharesOutstanding': 'common_stock_shares_outstanding'
}

QUARTERLY_BALANCE_SHEET_FLOAT_COLUMNS = [
    'total_assets', 'total_current_assets', 'cash_and_cash_equivalents',
    'cash_and_short_term_investments', 'inventory', 'current_net_receivables',
    'total_non_current_assets', 'property_plant_equipment', 'accumulated_depreciation_amortization_ppe',
    'intangible_assets', 'intangible_assets_excluding_goodwill', 'goodwill',
    'investments', 'long_term_investments', 'short_term_investments', 'other_current_assets',
    'other_non_current_assets', 'total_liabilities', 'total_current_liabilities',
    'current_accounts_payable', 'deferred_revenue', 'current_debt', 'short_term_debt',
    'total_non_current_liabilities', 'capital_lease_obligations', 'long_term_debt',
    'current_long_term_debt', 'long_term_debt_noncurrent', 'short_long_term_debt_total',
    'other_current_liabilities', 'other_non_current_liabilities', 'total_shareholder_equity',
    'treasury_stock', 'retained_earnings', 'common_stock'
]
QUARTERLY_BALANCE_SHEET_INT_COLUMNS = ['common_stock_shares_outstanding']

ANNUAL_CASH_FLOW_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'operatingCashflow': 'operating_cashflow',
    'paymentsForOperatingActivities': 'payments_for_operating_activities',
    'proceedsFromOperatingActivities': 'proceeds_from_operating_activities',
    'changeInOperatingLiabilities': 'change_in_operating_liabilities',
    'changeInOperatingAssets': 'change_in_operating_assets',
    'depreciationDepletionAndAmortization': 'depreciation_depletion_and_amortization',
    'capitalExpenditures': 'capital_expenditures',
    'changeInReceivables': 'change_in_receivables',
    'changeInInventory': 'change_in_inventory',
    'profitLoss': 'profit_loss',
    'cashflowFromInvestment': 'cashflow_from_investment',
    'cashflowFromFinancing': 'cashflow_from_financing',
    'proceedsFromRepaymentsOfShortTermDebt': 'proceeds_from_repayments_of_short_term_debt',
    'paymentsForRepurchaseOfCommonStock': 'payments_for_repurchase_of_common_stock',
    'paymentsForRepurchaseOfEquity': 'payments_for_repurchase_of_equity',
    'paymentsForRepurchaseOfPreferredStock': 'payments_for_repurchase_of_preferred_stock',
    'dividendPayout': 'dividend_payout',
    'dividendPayoutCommonStock': 'dividend_payout_common_stock',
    'dividendPayoutPreferredStock': 'dividend_payout_preferred_stock',
    'proceedsFromIssuanceOfCommonStock': 'proceeds_from_issuance_of_common_stock',
    'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
    'proceedsFromIssuanceOfPreferredStock': 'proceeds_from_issuance_of_preferred_stock',
    'proceedsFromRepurchaseOfEquity': 'proceeds_from_repurchase_of_equity',
    'proceedsFromSaleOfTreasuryStock': 'proceeds_from_sale_of_treasury_stock',
    'changeInCashAndCashEquivalents': 'change_in_cash_and_cash_equivalents',
    'changeInExchangeRate': 'change_in_exchange_rate',
    'netIncome': 'net_income',
}


QUARTERLY_CASH_FLOW_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'operatingCashflow': 'operating_cashflow',
    'paymentsForOperatingActivities': 'payments_for_operating_activities',
    'proceedsFromOperatingActivities': 'proceeds_from_operating_activities',
    'changeInOperatingLiabilities': 'change_in_operating_liabilities',
    'changeInOperatingAssets': 'change_in_operating_assets',
    'depreciationDepletionAndAmortization': 'depreciation_depletion_and_amortization',
    'capitalExpenditures': 'capital_expenditures',
    'changeInReceivables': 'change_in_receivables',
    'changeInInventory': 'change_in_inventory',
    'profitLoss': 'profit_loss',
    'cashflowFromInvestment': 'cashflow_from_investment',
    'cashflowFromFinancing': 'cashflow_from_financing',
    'proceedsFromRepaymentsOfShortTermDebt': 'proceeds_from_repayments_of_short_term_debt',
    'paymentsForRepurchaseOfCommonStock': 'payments_for_repurchase_of_common_stock',
    'paymentsForRepurchaseOfEquity': 'payments_for_repurchase_of_equity',
    'paymentsForRepurchaseOfPreferredStock': 'payments_for_repurchase_of_preferred_stock',
    'dividendPayout': 'dividend_payout',
    'dividendPayoutCommonStock': 'dividend_payout_common_stock',
    'dividendPayoutPreferredStock': 'dividend_payout_preferred_stock',
    'proceedsFromIssuanceOfCommonStock': 'proceeds_from_issuance_of_common_stock',
    'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
    'proceedsFromIssuanceOfPreferredStock': 'proceeds_from_issuance_of_preferred_stock',
    'proceedsFromRepurchaseOfEquity': 'proceeds_from_repurchase_of_equity',
    'proceedsFromSaleOfTreasuryStock': 'proceeds_from_sale_of_treasury_stock',
    'changeInCashAndCashEquivalents': 'change_in_cash_and_cash_equivalents',
    'changeInExchangeRate': 'change_in_exchange_rate',
    'netIncome': 'net_income',
}

ANNUAL_EARNINGS_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedEPS': 'reported_eps',
}

QUARTERLY_EARNINGS_MAP = {
    'symbol': 'symbol',
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedDate': 'reported_date',
    'reportedEPS': 'reported_eps',
    'estimatedEPS': 'estimated_eps',
    'surprise': 'surprise',
    'surprisePercentage': 'surprise_percentage',
    'reportTime': 'report_time',
}

INSIDER_TRANSACTION_MAP = {
    "transaction_date": "transaction_date",
    "ticker": "symbol",
    "executive": "executive",
    "executive_title": "executive_title",
    "security_type": "security_type",
    "acquisition_or_disposal": "acquisition_or_disposal",
    "shares": "shares",
    "share_price": "share_price",
}

STOCK_SPLIT_MAP = {
    "effective_date": "effective_date",
    "split_factor": "split_factor",
    "symbol": "symbol",
}

DIVIDENDS_MAP = {
    "ex_dividend_date": "ex_dividend_date",
    "declaration_date": "declaration_date",
    "record_date": "record_date",
    "payment_date": "payment_date",
    "amount": "amount",
    "symbol": "symbol"
}
