def standardize_company_fundamentals_columns(df):
    """Rename columns from Alpha Vantage to match the database schema."""

    column_map = {
    'Symbol': 'symbol',
    'AssetType': 'asset_type',
    'Name': 'name',
    'Description': 'description',
    'CIK': 'cik',
    'Exchange': 'exchange',
    'Currency': 'currency',
    'Country': 'country',
    'Sector': 'sector',
    'Industry': 'industry',
    'Address': 'address',
    'OfficialSite': 'official_site',
    'FiscalYearEnd': 'fiscal_year_end',
    'LatestQuarter': 'latest_quarter',
    'MarketCapitalization': 'market_capitalization',
    'EBITDA': 'ebitda',
    'PERatio': 'pe_ratio',
    'PEGRatio': 'peg_ratio',
    'BookValue': 'book_value',
    'DividendPerShare': 'dividend_per_share',
    'DividendYield': 'dividend_yield',
    'EPS': 'eps',
    'RevenuePerShareTTM': 'revenue_per_share_ttm',
    'ProfitMargin': 'profit_margin',
    'OperatingMarginTTM': 'operating_margin_ttm',
    'ReturnOnAssetsTTM': 'return_on_assets_ttm',
    'ReturnOnEquityTTM': 'return_on_equity_ttm',
    'RevenueTTM': 'revenue_ttm',
    'GrossProfitTTM': 'gross_profit_ttm',
    'DilutedEPSTTM': 'diluted_eps_ttm',
    'QuarterlyEarningsGrowthYOY': 'quarterly_earnings_growth_yoy',
    'QuarterlyRevenueGrowthYOY': 'quarterly_revenue_growth_yoy',
    'AnalystTargetPrice': 'analyst_target_price',
    'AnalystRatingStrongBuy': 'analyst_rating_strong_buy',
    'AnalystRatingBuy': 'analyst_rating_buy',
    'AnalystRatingHold': 'analyst_rating_hold',
    'AnalystRatingSell': 'analyst_rating_sell',
    'AnalystRatingStrongSell': 'analyst_rating_strong_sell',
    'TrailingPE': 'trailing_pe',
    'ForwardPE': 'forward_pe',
    'PriceToSalesRatioTTM': 'price_to_sales_ratio_ttm',
    'PriceToBookRatio': 'price_to_book_ratio',
    'EVToRevenue': 'ev_to_revenue',
    'EVToEBITDA': 'ev_to_ebitda',
    'Beta': 'beta',
    '52WeekHigh': 'fifty_two_week_high',
    '52WeekLow': 'fifty_two_week_low',
    '50DayMovingAverage': 'fifty_day_moving_average',
    '200DayMovingAverage': 'two_hundred_day_moving_average',
    'SharesOutstanding': 'shares_outstanding',
    'DividendDate': 'dividend_date',
    'ExDividendDate': 'ex_dividend_date'
}

    return df.rename(columns=column_map)


def standardize_annual_income_statement_columns(df):
    """Rename Alpha Vantage income statement columns to match the database schema."""
    
    column_map = {
        'symbol': 'symbol',
        'fiscalDateEnding': 'fiscal_date_ending',
        'reportedCurrency': 'reported_currency',
        'grossProfit': 'gross_profit',
        'totalRevenue': 'total_revenue',
        'costOfRevenue': 'cost_of_revenue',
        'costofGoodsAndServicesSold': 'cost_of_goods_and_services_sold',
        'operatingIncome': 'operating_income',
        'sellingGeneralAndAdministrative': 'selling_general_and_administrative',
        'researchAndDevelopment': 'research_and_development',
        'operatingExpenses': 'operating_expenses',
        'investmentIncomeNet': 'investment_income_net',
        'netInterestIncome': 'net_interest_income',
        'interestIncome': 'interest_income',
        'interestExpense': 'interest_expense',
        'nonInterestIncome': 'non_interest_income',
        'otherNonOperatingIncome': 'other_non_operating_income',
        'depreciation': 'depreciation',
        'depreciationAndAmortization': 'depreciation_and_amortization',
        'incomeBeforeTax': 'income_before_tax',
        'incomeTaxExpense': 'income_tax_expense',
        'interestAndDebtExpense': 'interest_and_debt_expense',
        'netIncomeFromContinuingOperations': 'net_income_from_continuing_operations',
        'comprehensiveIncomeNetOfTax': 'comprehensive_income_net_of_tax',
        'ebit': 'ebit',
        'ebitda': 'ebitda',
        'netIncome': 'net_income',
    }

    return df.rename(columns=column_map)


def standardize_quarterly_income_statement_columns(df):
    """Rename Alpha Vantage quarterly income statement columns to match the database schema."""

    column_map = {
        'symbol': 'symbol',
        'fiscalDateEnding': 'fiscal_date_ending',
        'reportedCurrency': 'reported_currency',
        'grossProfit': 'gross_profit',
        'totalRevenue': 'total_revenue',
        'costOfRevenue': 'cost_of_revenue',
        'costofGoodsAndServicesSold': 'cost_of_goods_and_services_sold',
        'operatingIncome': 'operating_income',
        'sellingGeneralAndAdministrative': 'selling_general_and_administrative',
        'researchAndDevelopment': 'research_and_development',
        'operatingExpenses': 'operating_expenses',
        'investmentIncomeNet': 'investment_income_net',
        'netInterestIncome': 'net_interest_income',
        'interestIncome': 'interest_income',
        'interestExpense': 'interest_expense',
        'nonInterestIncome': 'non_interest_income',
        'otherNonOperatingIncome': 'other_non_operating_income',
        'depreciation': 'depreciation',
        'depreciationAndAmortization': 'depreciation_and_amortization',
        'incomeBeforeTax': 'income_before_tax',
        'incomeTaxExpense': 'income_tax_expense',
        'interestAndDebtExpense': 'interest_and_debt_expense',
        'netIncomeFromContinuingOperations': 'net_income_from_continuing_operations',
        'comprehensiveIncomeNetOfTax': 'comprehensive_income_net_of_tax',
        'ebit': 'ebit',
        'ebitda': 'ebitda',
        'netIncome': 'net_income',
    }

    return df.rename(columns=column_map)

def standardize_annual_balance_sheet_columns(df):
    """Rename Alpha Vantage annual balance sheet columns to match database schema."""
    column_map = {
        'symbol': 'symbol',
        'fiscalDateEnding': 'fiscal_date_ending',
        'reportedCurrency': 'reported_currency',
        'totalAssets': 'total_assets',
        'totalCurrentAssets': 'total_current_assets',
        'cashAndCashEquivalentsAtCarryingValue': 'cash_and_cash_equivalents',
        'cashAndShortTermInvestments': 'cash_and_short_term_investments',
        'inventory': 'inventory',
        'currentNetReceivables': 'current_net_receivables',
        'totalNonCurrentAssets': 'total_non_current_assets',
        'propertyPlantEquipment': 'property_plant_equipment',
        'accumulatedDepreciationAmortizationPPE': 'accumulated_depreciation_amortization_ppe',
        'intangibleAssets': 'intangible_assets',
        'goodwill': 'goodwill',
        'longTermInvestments': 'long_term_investments',
        'shortTermInvestments': 'short_term_investments',
        'otherCurrentAssets': 'other_current_assets',
        'otherNonCurrentAssets': 'other_non_current_assets',
        'totalLiabilities': 'total_liabilities',
        'totalCurrentLiabilities': 'total_current_liabilities',
        'currentAccountsPayable': 'current_accounts_payable',
        'deferredRevenue': 'deferred_revenue',
        'currentDebt': 'current_debt',
        'shortTermDebt': 'short_term_debt',
        'totalNonCurrentLiabilities': 'total_non_current_liabilities',
        'capitalLeaseObligations': 'capital_lease_obligations',
        'longTermDebt': 'long_term_debt',
        'shortLongTermDebtTotal': 'short_long_term_debt_total',
        'otherCurrentLiabilities': 'other_current_liabilities',
        'otherNonCurrentLiabilities': 'other_non_current_liabilities',
        'totalShareholderEquity': 'total_shareholder_equity',
        'treasuryStock': 'treasury_stock',
        'retainedEarnings': 'retained_earnings',
        'commonStock': 'common_stock',
        'commonStockSharesOutstanding': 'common_stock_shares_outstanding',
    }
    return df.rename(columns=column_map)

def standardize_quarterly_balance_sheet_columns(df):
    """Rename Alpha Vantage quarterly balance sheet columns to match database schema."""
    column_map = {
        'symbol': 'symbol',
        'fiscalDateEnding': 'fiscal_date_ending',
        'reportedCurrency': 'reported_currency',
        'totalAssets': 'total_assets',
        'totalCurrentAssets': 'total_current_assets',
        'cashAndCashEquivalentsAtCarryingValue': 'cash_and_cash_equivalents',
        'cashAndShortTermInvestments': 'cash_and_short_term_investments',
        'inventory': 'inventory',
        'currentNetReceivables': 'current_net_receivables',
        'totalNonCurrentAssets': 'total_non_current_assets',
        'propertyPlantEquipment': 'property_plant_equipment',
        'accumulatedDepreciationAmortizationPPE': 'accumulated_depreciation_amortization_ppe',
        'intangibleAssets': 'intangible_assets',
        'goodwill': 'goodwill',
        'longTermInvestments': 'long_term_investments',
        'shortTermInvestments': 'short_term_investments',
        'otherCurrentAssets': 'other_current_assets',
        'otherNonCurrentAssets': 'other_non_current_assets',
        'totalLiabilities': 'total_liabilities',
        'totalCurrentLiabilities': 'total_current_liabilities',
        'currentAccountsPayable': 'current_accounts_payable',
        'deferredRevenue': 'deferred_revenue',
        'currentDebt': 'current_debt',
        'shortTermDebt': 'short_term_debt',
        'totalNonCurrentLiabilities': 'total_non_current_liabilities',
        'capitalLeaseObligations': 'capital_lease_obligations',
        'longTermDebt': 'long_term_debt',
        'shortLongTermDebtTotal': 'short_long_term_debt_total',
        'otherCurrentLiabilities': 'other_current_liabilities',
        'otherNonCurrentLiabilities': 'other_non_current_liabilities',
        'totalShareholderEquity': 'total_shareholder_equity',
        'treasuryStock': 'treasury_stock',
        'retainedEarnings': 'retained_earnings',
        'commonStock': 'common_stock',
        'commonStockSharesOutstanding': 'common_stock_shares_outstanding',
    }
    return df.rename(columns=column_map)
